apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
      - name: welcome-app
        image: spyronx123/welcome-pl-app:2.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8087

---
apiVersion: v1
kind: Service
metadata:
  name: welcome-app
spec:
  selector:
    app: welcome-app
  ports:
  - port: 8087
    targetPort: 8087
  type: NodePort

